# Generated by Django 5.2.12 on 2026-04-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shortenedlink_custom_alias_shortenedlink_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='original_url',
            field=models.URLField(max_length=10000),
        ),
    ]
