# Generated by Django 5.2.12 on 2026-04-17 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shortenedlink_original_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedlink',
            name='is_archived',
        ),
        migrations.AddIndex(
            model_name='shortenedlink',
            index=models.Index(fields=['short_code', 'is_active'], name='core_shorte_short_c_0d5b68_idx'),
        ),
    ]
