# Generated by Django 5.2.13 on 2026-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='device',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
